apiVersion: v1
kind: Namespace
metadata:
  name: cozlive
  labels:
    name: cozlive
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cozlive-staging
  labels:
    name: cozlive-staging
    environment: staging
